version: '3'
services: 
    database:
        image: mysql
        container_name: auth_app_database
        ports: 
            - 3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: PASSWORD
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
        volumes: 
            - ./data:/var/lib/mysql
    backend:
        build: ./docker/backend
        container_name: auth_app_backend
        ports: 
            - 8000:80
        tty: true
        volumes: 
            - ./backend:/workspace
    proxy:
        build: ./docker/proxy
        container_name: auth_app_proxy
        ports: 
            - 8080:443
        tty: true
    frontend:
        build: ./docker/frontend
        container_name: auth_app_frontend
        tty: true
        working_dir: /workspace
        environment:
            TZ: "Asia/Tokyo"
        volumes:
            - "./frontend:/workspace"